steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=capturio-keyring
      - --key=cloudbuild-env-config
  # Install yarn dependencies
  - name: node:12.16.2
    entrypoint: yarn
    args: ['install']
  # Build
  - name: node:12.16.2
    entrypoint: yarn
    args: ["build:webapp"]
  # Deploy
  - name: node:12.16.2
    entrypoint: yarn
    args: ["deploy"]

